### ISSUE TITLE
Is it possible to create a subprocess for the add-on?

### ISSUE THREAD

**Issue by Magic-wei** [cesarhuret/docGPT#1]
Hi cesarhuret, 

Thank you for making this interesting tool for Microsoft Word! I just tested it on my machine, and as you said in README, Word became temporarily unresponsive while waiting for the result from ChatGPT. This could be extremely long when I asked some hard questions. I was wondering is it possible to create a subprocess such that I can use Word when I am waiting for the result? I believe this will give the user a much better experience.

**Comment by cesarhuret** [comment]
Hey @Magic-wei!

Definitely, this is something I need to work on, haven't had much time to do so, but within the next week I should be able to get something done. 

Thanks for mentioning this!

**Comment by Magic-wei** [comment]
Hi @cesarhuret, I noticed that you're using ` req.Open "POST", "https://chatgpt-api.kesarx.repl.co/chat", False` which sets sync mode and thus makes Word temporarily unresponsive for a while. I tried to change `False` to `True`, i.e. async mode, but here comes a weird thing: I cannot get any input from keyboard before remote response arrives but the mouse input still works. Do you have any idea on this?

**Comment by Magic-wei** [comment]
Word add-on has been updated to async mode (PR #10), which allows the users to use Word as usual (except for keyboard input issue #9) while waiting for the response from ChatGPT.
