### ISSUE TITLE
Run-time error '-2147352319 (80020101)': Could not complete the operation due to error 80020101.

### ISSUE THREAD

**Issue by IIIIIIIllllllllIIIII** [cesarhuret/docGPT#11]
![image](https://user-images.githubusercontent.com/113683801/224565475-e4bf5dac-fba2-44fd-9b10-d176d28dbc1e.png)

**Comment by IIIIIIIllllllllIIIII** [comment]
oh - this is in microsoft word....

**Comment by IIIIIIIllllllllIIIII** [comment]
found the error - if you mark any "empty space" it will not work. you have to work words and letters, nothing else!

**Comment by Magic-wei** [comment]
Hi @Gitterman69, the latest version of docGPT works well on my machine, with Windows 10 and Word 2016. Can you describe more details about this issue? What do you mean by "empty space"?

**Comment by BarryTheShen** [comment]
@Magic-wei Same problem, it does work for word 2016 but it doesn't for word 2021

**Comment by Magic-wei** [comment]
@BarryTheShen Thank you for the information. Will find a machine with Word 2021 to debug.

BTW, to make the issue more clear, can you offer some prompts that can cause the issue?

**Comment by BarryTheShen** [comment]
@Magic-wei I think any prompt works

**Comment by Magic-wei** [comment]
@BarryTheShen For example, asking "" (nothing selected), "PySide6" or "Write an PySide6 example" can all cause the issue, right?

**Comment by BarryTheShen** [comment]
I think yes

**Comment by Magic-wei** [comment]
@BarryTheShen @Gitterman69 Tested on Word 2021, Word 2019 and Word 2016:
- Works perfect with Word 2016 and Word 2019.
- Asking "" (nothing selected) has chance to cause `80072ee2` error (request timeout) with Word 2021, whereas prompts like "PySide6" and "Write an PySide6 example" work well.

So with Word 2021, it is recommended to select some words to ask ChatGPT and it should work well; with Word 2019 and Word 2016, no issue is observed.

**Comment by BarryTheShen** [comment]
Ok thank you

**Comment by thegrince** [comment]
Hello,
Same error here but cause is Error 404 on https://chatgpt-api.kesarx.repl.co/chat
