### ISSUE TITLE
how could I use this tool to ask CHATGPT to translate the text into English in Word

### ISSUE THREAD

**Issue by SamuelWeng0919** [cesarhuret/docGPT#16]
Is there any way I can ask ChatGPT to translate the text into English in Word?
Thanks

**Comment by cesarhuret** [comment]
Sure, in the highlighted text, you could probably add something like "please translate the text above into English". 

Lmk if that works so that I can close this issue.

**Comment by SamuelWeng0919** [comment]
Yes. It works. Thanks a lot
