### ISSUE TITLE
Error 502 when trying to run the script

### ISSUE THREAD

**Issue by StrawberryFields0** [cesarhuret/docGPT#3]
Getting HTTP error 502 response when trying to run script 
"Exception: Request failed for https://chatgpt-api.kesarx.repl.co returned code 502. Truncated server response: <!DOCTYPE html> <html lang="en"> <head> <title>Unable To Wake Up</title> <link rel="stylesheet" href="https://fonts.googleapis.... (use muteHttpExceptions option to examine full response)"
Update just saw it was discontinued lol my bad

**Comment by cesarhuret** [comment]
Hey @StrawberryFields0 !
I just updated the project, so feel free to try it out and let me know if it works so that I can close this issue!
